import { createContext, useContext, useEffect, useMemo, useState } from "react";

const languages = {
	pt: { locale: "pt-PT", label: "Português" },
	en: { locale: "en", label: "English" },
	es: { locale: "es", label: "Español" },
	fr: { locale: "fr", label: "Français" },
	de: { locale: "de", label: "Deutsch" },
};

const translations = {
	pt: {},
	en: {
		"Falar com especialista": "Speak with a specialist", "Fale com um especialista": "Speak with a specialist",
		"Mais clareza.": "More clarity.", "Mais presença": "More presence", "Mais resultados.": "More results.",
		"Como funciona": "How it works", "O que está incluído no preço": "What's included in the price", "Planos e Pacotes": "Plans and packages",
		"Prova social": "Social proof", "Autoridade": "Authority", "Dúvidas Frequentes (FAQ)": "Frequently asked questions (FAQ)",
		"Fale com a nossa equipe": "Talk to our team", "Nome": "Name", "Localização": "Location", "Telefone": "Phone", "Serviços": "Services", "Mensagem": "Message", "Enviar": "Send", "Enviando...": "Sending...",
		"Selecione um serviço": "Select a service", "Digite seu país": "Enter your country", "Digite seu telefone": "Enter your phone number", "Seu nome ou da sua empresa": "Your or your company's name", "Nos conte mais sobre seu projeto (Opcional)": "Tell us more about your project (Optional)",
	},
	es: {
		"Falar com especialista": "Hablar con un especialista", "Fale com um especialista": "Hable con un especialista",
		"Mais clareza.": "Más claridad.", "Mais presença": "Más presencia", "Mais resultados.": "Más resultados.",
		"Como funciona": "Cómo funciona", "O que está incluído no preço": "Qué está incluido en el precio", "Planos e Pacotes": "Planes y paquetes",
		"Prova social": "Prueba social", "Autoridade": "Autoridad", "Dúvidas Frequentes (FAQ)": "Preguntas frecuentes (FAQ)",
		"Fale com a nossa equipe": "Hable con nuestro equipo", "Nome": "Nombre", "Localização": "Ubicación", "Telefone": "Teléfono", "Serviços": "Servicios", "Mensagem": "Mensaje", "Enviar": "Enviar", "Enviando...": "Enviando...",
		"Selecione um serviço": "Seleccione un servicio", "Digite seu país": "Escriba su país", "Digite seu telefone": "Escriba su teléfono", "Seu nome ou da sua empresa": "Su nombre o el de su empresa", "Nos conte mais sobre seu projeto (Opcional)": "Cuéntenos más sobre su proyecto (Opcional)",
	},
	fr: {
		"Falar com especialista": "Parler à un spécialiste", "Fale com um especialista": "Parlez à un spécialiste",
		"Mais clareza.": "Plus de clarté.", "Mais presença": "Plus de présence", "Mais resultados.": "Plus de résultats.",
		"Como funciona": "Comment ça marche", "O que está incluído no preço": "Ce qui est inclus dans le prix", "Planos e Pacotes": "Forfaits et offres",
		"Prova social": "Preuve sociale", "Autoridade": "Autorité", "Dúvidas Frequentes (FAQ)": "Questions fréquentes (FAQ)",
		"Fale com a nossa equipe": "Parlez à notre équipe", "Nome": "Nom", "Localização": "Localisation", "Telefone": "Téléphone", "Serviços": "Services", "Mensagem": "Message", "Enviar": "Envoyer", "Enviando...": "Envoi...",
		"Selecione um serviço": "Sélectionnez un service", "Digite seu país": "Saisissez votre pays", "Digite seu telefone": "Saisissez votre téléphone", "Seu nome ou da sua empresa": "Votre nom ou celui de votre entreprise", "Nos conte mais sobre seu projeto (Opcional)": "Parlez-nous de votre projet (Facultatif)",
	},
	de: {
		"Falar com especialista": "Mit einem Experten sprechen", "Fale com um especialista": "Sprechen Sie mit einem Experten",
		"Mais clareza.": "Mehr Klarheit.", "Mais presença": "Mehr Präsenz", "Mais resultados.": "Mehr Ergebnisse.",
		"Como funciona": "So funktioniert es", "O que está incluído no preço": "Was im Preis enthalten ist", "Planos e Pacotes": "Pläne und Pakete",
		"Prova social": "Social Proof", "Autoridade": "Kompetenz", "Dúvidas Frequentes (FAQ)": "Häufige Fragen (FAQ)",
		"Fale com a nossa equipe": "Sprechen Sie mit unserem Team", "Nome": "Name", "Localização": "Standort", "Telefone": "Telefon", "Serviços": "Leistungen", "Mensagem": "Nachricht", "Enviar": "Senden", "Enviando...": "Wird gesendet...",
		"Selecione um serviço": "Wählen Sie eine Leistung", "Digite seu país": "Geben Sie Ihr Land ein", "Digite seu telefone": "Geben Sie Ihre Telefonnummer ein", "Seu nome ou da sua empresa": "Ihr Name oder der Ihres Unternehmens", "Nos conte mais sobre seu projeto (Opcional)": "Erzählen Sie uns mehr über Ihr Projekt (Optional)",
	},
};

Object.assign(translations.en, {
	"Ex: Minhaempresa@gmail.com": "E.g.: Mycompany@gmail.com",
	"Preencha os dados abaixo para receber nosso contato via WhatsApp.": "Fill in the details below to receive our contact via WhatsApp.",
	"Por favor, escolha o país de origem no campo de localização": "Please choose your country of origin in the location field",
});
Object.assign(translations.es, {
	"Ex: Minhaempresa@gmail.com": "Ej.: Miempresa@gmail.com",
	"Preencha os dados abaixo para receber nosso contato via WhatsApp.": "Completa los datos para recibir nuestro contacto por WhatsApp.",
	"Por favor, escolha o país de origem no campo de localização": "Elige tu país de origen en el campo de ubicación",
});
Object.assign(translations.fr, {
	"Ex: Minhaempresa@gmail.com": "Ex. : Monentreprise@gmail.com",
	"Preencha os dados abaixo para receber nosso contato via WhatsApp.": "Remplissez les informations ci-dessous pour être contacté via WhatsApp.",
	"Por favor, escolha o país de origem no campo de localização": "Veuillez choisir votre pays d'origine dans le champ de localisation",
});
Object.assign(translations.de, {
	"Ex: Minhaempresa@gmail.com": "Z. B.: Meinunternehmen@gmail.com",
	"Preencha os dados abaixo para receber nosso contato via WhatsApp.": "Füllen Sie die folgenden Angaben aus, damit wir Sie über WhatsApp kontaktieren können.",
	"Por favor, escolha o país de origem no campo de localização": "Bitte wählen Sie Ihr Herkunftsland im Standortfeld aus",
});
Object.assign(translations.en, {
	"Produção de conteúdo de alta qualidade de ponta a ponta.": "High-quality end-to-end content production.",
});
Object.assign(translations.es, {
	"Produção de conteúdo de alta qualidade de ponta a ponta.": "Producción de contenido de alta calidad de principio a fin.",
});
Object.assign(translations.fr, {
	"Produção de conteúdo de alta qualidade de ponta a ponta.": "Production de contenu de haute qualité de bout en bout.",
});
Object.assign(translations.de, {
	"Produção de conteúdo de alta qualidade de ponta a ponta.": "Hochwertige Content-Produktion von Anfang bis Ende.",
});

// Text rendered by the landing page is intentionally kept in Portuguese in the
// components.  This dictionary lets a language change update that complete
// rendered page without duplicating the layout for every locale.
const pageTranslations = {
	en: {
		"Início": "Home", "Benefícios": "Benefits", "Incluído": "Included", "Prova Social": "Social proof", "Planos": "Plans", "Contato": "Contact", "Falar com especialista": "Speak with a specialist", "Fechar menu": "Close menu", "Abrir menu": "Open menu",
		"Eu crio o roteiro, vou até si gravar e entrego o vídeo pronto.": "I write the script, come to film you and deliver the finished video.", "Produção de conteúdo de alta qualidade de": "High-quality", "ponta a ponta.": "end-to-end content production.", "Quero Potencializar os meus vídeos": "I want to boost my videos", "FALAR CONOSCO": "CONTACT US", "Pronto em 3 dias úteis": "Ready in 3 business days", "Sem fidelidade": "No long-term commitment",
		"Acompanhe nossos últimos Reels": "Follow our latest Reels", "Conteúdo exclusivo sobre marketing, estratégia e crescimento para empresas.": "Exclusive content about marketing, strategy and business growth.", "Carregando Reels...": "Loading Reels...", "Ver mais Reels no Instagram": "See more Reels on Instagram", "São apenas 4 passos para o conteúdo perfeito.": "Just 4 steps to perfect content.", "O que está incluído no preço": "What's included in the price", "Tudo o que precisa para um vídeo profissional. Sem custos surpresa.": "Everything you need for a professional video. No surprise costs.", "Escolha o plano ideal para a sua estratégia de conteúdo.": "Choose the ideal plan for your content strategy.", "Mais Escolhido": "Most popular", "Precisa apenas da edição?": "Only need editing?", "Quero apenas o serviço de edição": "I only want the editing service", "As perguntas que todos fazem.": "The questions everyone asks.", "Prova social": "Social proof", "Portfólio de vídeos": "Video portfolio", "Prints de WhatsApp": "WhatsApp screenshots", "Depoimentos em vídeo": "Video testimonials", "Criar é o começo. Potencializar é o que nos move.": "Creating is the beginning. Boosting is what drives us.", "Países de atuação": "Countries we serve", "Todos os direitos reservados.": "All rights reserved.",
	},
	es: { "Início": "Inicio", "Benefícios": "Beneficios", "Como funciona": "Cómo funciona", "Incluído": "Incluido", "Prova Social": "Prueba social", "Planos": "Planes", "Autoridade": "Autoridad", "Contato": "Contacto", "Falar com especialista": "Hablar con un especialista", "Fechar menu": "Cerrar menú", "Abrir menu": "Abrir menú", "Mais clareza.": "Más claridad.", "Mais presença": "Más presencia", "Mais resultados.": "Más resultados.", "Eu crio o roteiro, vou até si gravar e entrego o vídeo pronto.": "Creo el guion, voy a grabarte y te entrego el vídeo listo.", "Quero Potencializar os meus vídeos": "Quiero potenciar mis vídeos", "FALAR CONOSCO": "HABLE CON NOSOTROS", "Pronto em 3 dias úteis": "Listo en 3 días laborables", "Sem fidelidade": "Sin permanencia", "Acompanhe nossos últimos Reels": "Sigue nuestros últimos Reels", "Carregando Reels...": "Cargando Reels...", "Ver mais Reels no Instagram": "Ver más Reels en Instagram", "São apenas 4 passos para o conteúdo perfeito.": "Solo 4 pasos para el contenido perfecto.", "Tudo o que precisa para um vídeo profissional. Sem custos surpresa.": "Todo lo que necesitas para un vídeo profesional. Sin costes sorpresa.", "Mais Escolhido": "Más elegido", "As perguntas que todos fazem.": "Las preguntas que todos hacen.", "Criar é o começo. Potencializar é o que nos move.": "Crear es el comienzo. Potenciar es lo que nos mueve.", "Países de atuação": "Países donde trabajamos", "Todos os direitos reservados.": "Todos los derechos reservados." },
	fr: { "Início": "Accueil", "Benefícios": "Avantages", "Como funciona": "Comment ça marche", "Incluído": "Inclus", "Prova Social": "Preuve sociale", "Planos": "Forfaits", "Autoridade": "Expertise", "Contato": "Contact", "Falar com especialista": "Parler à un spécialiste", "Fechar menu": "Fermer le menu", "Abrir menu": "Ouvrir le menu", "Mais clareza.": "Plus de clarté.", "Mais presença": "Plus de présence", "Mais resultados.": "Plus de résultats.", "Eu crio o roteiro, vou até si gravar e entrego o vídeo pronto.": "J'écris le scénario, je viens vous filmer et je vous livre la vidéo terminée.", "Quero Potencializar os meus vídeos": "Je veux booster mes vidéos", "FALAR CONOSCO": "NOUS CONTACTER", "Pronto em 3 dias úteis": "Prêt en 3 jours ouvrés", "Sem fidelidade": "Sans engagement", "Acompanhe nossos últimos Reels": "Découvrez nos derniers Reels", "Carregando Reels...": "Chargement des Reels...", "Ver mais Reels no Instagram": "Voir plus de Reels sur Instagram", "São apenas 4 passos para o conteúdo perfeito.": "Seulement 4 étapes vers le contenu parfait.", "Tudo o que precisa para um vídeo profissional. Sem custos surprise.": "Tout ce dont vous avez besoin pour une vidéo professionnelle. Sans frais surprises.", "Mais Escolhido": "Le plus choisi", "As perguntas que todos fazem.": "Les questions que tout le monde pose.", "Criar é o começo. Potencializar é o que nos move.": "Créer est le début. Booster est ce qui nous anime.", "Países de atuação": "Pays desservis", "Todos os direitos reservados.": "Tous droits réservés." },
	de: { "Início": "Startseite", "Benefícios": "Vorteile", "Como funciona": "So funktioniert es", "Incluído": "Enthalten", "Prova Social": "Social Proof", "Planos": "Pakete", "Autoridade": "Kompetenz", "Contato": "Kontakt", "Falar com especialista": "Mit einem Experten sprechen", "Fechar menu": "Menü schließen", "Abrir menu": "Menü öffnen", "Mais clareza.": "Mehr Klarheit.", "Mais presença": "Mehr Präsenz", "Mais resultados.": "Mehr Ergebnisse.", "Eu crio o roteiro, vou até si gravar e entrego o vídeo pronto.": "Ich schreibe das Drehbuch, komme zum Filmen und liefere das fertige Video.", "Produção de conteúdo de alta qualidade de": "Hochwertige Content-Produktion", "ponta a ponta.": "aus einer Hand.", "Quero Potencializar os meus vídeos": "Ich möchte meine Videos stärken", "FALAR CONOSCO": "KONTAKTIEREN SIE UNS", "Pronto em 3 dias úteis": "Fertig in 3 Werktagen", "Sem fidelidade": "Keine Vertragsbindung", "Acompanhe nossos últimos Reels": "Sehen Sie unsere neuesten Reels", "Conteúdo exclusivo sobre marketing, estratégia e crescimento para empresas.": "Exklusive Inhalte über Marketing, Strategie und Unternehmenswachstum.", "Carregando Reels...": "Reels werden geladen...", "Ver mais Reels no Instagram": "Mehr Reels auf Instagram ansehen", "São apenas 4 passos para o conteúdo perfeito.": "Nur 4 Schritte zum perfekten Inhalt.", "Estratégia e Roteiro": "Strategie und Drehbuch", "A Gravação (Eu vou até si)": "Dreh (ich komme zu Ihnen)", "A Magia da Edição": "Die Magie des Schnitts", "Vídeos na sua mão": "Videos in Ihren Händen", "Tudo o que precisa para um vídeo profissional. Sem custos surpresa.": "Alles für ein professionelles Video. Ohne Überraschungskosten.", "Escolha o plano ideal para a sua estratégia de conteúdo.": "Wählen Sie den idealen Plan für Ihre Content-Strategie.", "Mais Escolhido": "Am beliebtesten", "Precisa apenas da edição?": "Benötigen Sie nur den Schnitt?", "Quero apenas o serviço de edição": "Ich möchte nur den Schnittservice", "As perguntas que todos fazem.": "Die Fragen, die alle stellen.", "Prova social": "Social Proof", "Portfólio de vídeos": "Video-Portfolio", "Prints de WhatsApp": "WhatsApp-Screenshots", "Depoimentos em vídeo": "Video-Referenzen", "Criar é o começo. Potencializar é o que nos move.": "Schaffen ist der Anfang. Potenzial zu entfalten treibt uns an.", "Países de atuação": "Länder, in denen wir tätig sind", "Todos os direitos reservados.": "Alle Rechte vorbehalten." },
};

const additionalPageTranslations = {
	en: {
		"Não se preocupe com o que dizer, nem como gravar ou editar. A ": "Don't worry about what to say, how to film or edit. ",
		" cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": " takes care of everything and delivers your finished videos within 3 business days.",
		"Estratégia e Roteiro": "Strategy and scripting", "A Gravação (Eu vou até si)": "Filming (I come to you)", "A Magia da Edição": "The magic of editing", "Vídeos na sua mão": "Videos in your hands",
		"Analisamos o seu objetivo e eu crio os roteiros altamente persuasivos e virais. Você só tem de aprovar.": "We analyse your goal and create highly persuasive, viral scripts. You just need to approve them.",
		"Marcamos o dia, eu vou ao seu espaço físico, ajusto o ambiente, dirijo a cena para ficar confortável e gravamos tudo com alta qualidade.": "We schedule the day, I come to your location, set up the environment, direct the scene to keep you comfortable and film everything in high quality.",
		"Pego em todo o material gravado, levo para a ilha de edição e aplico retenção pura: cortes, legendas, efeitos e correção de cor.": "I take all the recorded material to the editing suite and maximise retention with cuts, captions, effects and colour correction.",
		"Em até 3 dias úteis após a gravação, os seus vídeos estão prontos numa pasta do Google Drive. É só descarregar e publicar.": "Within 3 business days of filming, your videos are ready in a Google Drive folder. Just download and publish.",
		"Roteiros Estratégicos": "Strategic scripts", "Textos pensados para reter a atenção e converter seguidores em clientes.": "Copy designed to hold attention and turn followers into customers.", "Direção de Gravação": "Filming direction", "Ajudo-o com a postura, tom de voz e naturalidade em frente às câmaras.": "I help you with posture, tone of voice and confidence in front of the cameras.", "Legendas que prendem": "Captivating captions", "As palavras aparecem no ecrã no ritmo certo, com cores e fontes que combinam com a sua marca.": "Words appear on screen at the right pace, with colours and fonts that match your brand.", "Som limpo e Imagem tratada": "Clean sound and polished image", "Remoção de ruídos de fundo e correção de luz e cor.": "Background noise removal and light and colour correction.", "Imagens extra (B-rolls)": "Extra footage (B-roll)", "Adicionamos cenas com direitos pagos para ilustrar o que está a dizer e manter o vídeo dinâmico.": "We add licensed footage to illustrate what you are saying and keep the video dynamic.", "Atendimento Direto": "Direct support", "Fala diretamente comigo no WhatsApp. Sem robôs, sem intermediários.": "Speak directly with me on WhatsApp. No bots, no middlemen.",
		"Todos os pacotes mensais incluem: Roteiro, Gravação Presencial, Edição completa e Entrega em 3 dias úteis.": "All monthly packages include: scripting, on-site filming, complete editing and delivery within 3 business days.", "Essencial": "Essential", "Crescimento": "Growth", "Aceleração": "Acceleration", "Autoridade": "Authority", "4 vídeos por mês": "4 videos per month", "6 vídeos por mês": "6 videos per month", "10 vídeos por mês": "10 videos per month", "15 vídeos por mês": "15 videos per month", "Roteiro": "Scripting", "Gravação presencial": "On-site filming", "Edição completa": "Complete editing", "Entrega em 3 dias úteis": "Delivery within 3 business days", "Escolher Essencial": "Choose Essential", "Escolher Crescimento": "Choose Growth", "Escolher Aceleração": "Choose Acceleration", "Escolher Autoridade": "Choose Authority", "O material bruto deve ser enviado previamente para análise técnica.": "Raw footage must be sent in advance for technical analysis.", "60€/vídeo": "EUR 60/video",
		"Trabalho real, marca forte e conteúdo que sustenta a percepção de valor.": "Real work, a strong brand and content that sustains perceived value.", "Pronto para impulsionar sua marca com autoridade?": "Ready to boost your brand with authority?", "Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de ": "Connect with our team of experts and accelerate conversions with smart campaigns and content with ", "Impacto": "Impact",
		"Vai realizar ou participar num evento? Seremos os seus olhos ": "Hosting or attending an event? We will be your eyes ", "e a sua câmera": "and your camera", "O serviço premium de Storymaker exclusivo para empresários que não podem perder tempo a segurar no telemóvel.": "The premium Storymaker service for business owners who cannot afford to spend time holding a phone.", "Capto os bastidores e os momentos-chave em tempo real.": "I capture behind-the-scenes footage and key moments in real time.", "Gravo conteúdos dinâmicos para os Stories e para o Feed com um olhar cinematográfico.": "I record dynamic content for Stories and the Feed with a cinematic eye.", "Transmito a energia e a autoridade do seu evento para quem está a ver de casa, enquanto tudo acontece.": "I convey the energy and authority of your event to those watching from home as it happens.", "Não deixe que o seu maior evento passe em branco nas redes sociais.": "Don't let your biggest event go unnoticed on social media.", "Quero um Storymaker para o meu próximo evento": "I want a Storymaker for my next event",
	},
	es: {
		"Não se preocupe com o que dizer, nem como gravar ou editar. A ": "No te preocupes por qué decir, ni por cómo grabar o editar. ", " cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": " se encarga de todo y entrega tus vídeos listos en hasta 3 días laborables.", "Estratégia e Roteiro": "Estrategia y guion", "A Gravação (Eu vou até si)": "La grabación (voy hasta ti)", "A Magia da Edição": "La magia de la edición", "Vídeos na sua mão": "Vídeos en tus manos", "Roteiros Estratégicos": "Guiones estratégicos", "Direção de Gravação": "Dirección de grabación", "Legendas que prendem": "Subtítulos que enganchan", "Som limpo e Imagem tratada": "Sonido limpio e imagen tratada", "Imagens extra (B-rolls)": "Imágenes extra (B-roll)", "Atendimento Direto": "Atención directa", "Trabalho real, marca forte e conteúdo que sustenta a percepção de valor.": "Trabajo real, marca fuerte y contenido que sostiene la percepción de valor.", "Pronto para impulsionar sua marca com autoridade?": "¿Listo para impulsar tu marca con autoridad?", "Impacto": "Impacto", "Quero um Storymaker para o meu próximo evento": "Quiero un Storymaker para mi próximo evento",
		"Todos os pacotes mensais incluem: Roteiro, Gravação Presencial, Edição completa e Entrega em 3 dias úteis.": "Todos los paquetes mensuales incluyen: guion, grabación presencial, edición completa y entrega en 3 días laborables.", "Essencial": "Esencial", "Crescimento": "Crecimiento", "Aceleração": "Aceleración", "Autoridade": "Autoridad", "4 vídeos por mês": "4 vídeos al mes", "6 vídeos por mês": "6 vídeos al mes", "10 vídeos por mês": "10 vídeos al mes", "15 vídeos por mês": "15 vídeos al mes", "Roteiro": "Guion", "Gravação presencial": "Grabación presencial", "Edição completa": "Edición completa", "Entrega em 3 dias úteis": "Entrega en 3 días laborables", "Escolher Essencial": "Elegir Esencial", "Escolher Crescimento": "Elegir Crecimiento", "Escolher Aceleração": "Elegir Aceleración", "Escolher Autoridade": "Elegir Autoridad", "O material bruto deve ser enviado previamente para análise técnica.": "El material bruto debe enviarse previamente para un análisis técnico.", "60€/vídeo": "60€/vídeo",
	},
	fr: {
		"Não se preocupe com o que dizer, nem como gravar ou editar. A ": "Ne vous inquiétez pas de quoi dire, ni de comment filmer ou monter. ", " cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": " s'occupe de tout et livre vos vidéos prêtes sous 3 jours ouvrés.", "Estratégia e Roteiro": "Stratégie et scénario", "A Gravação (Eu vou até si)": "Le tournage (je viens à vous)", "A Magia da Edição": "La magie du montage", "Vídeos na sua mão": "Des vidéos entre vos mains", "Roteiros Estratégicos": "Scénarios stratégiques", "Direção de Gravação": "Direction du tournage", "Legendas que prendem": "Des sous-titres captivants", "Som limpo e Imagem tratada": "Son propre et image retouchée", "Imagens extra (B-rolls)": "Images supplémentaires (B-roll)", "Atendimento Direto": "Accompagnement direct", "Trabalho real, marca forte e conteúdo que sustenta a percepção de valor.": "Du travail réel, une marque forte et un contenu qui soutient la valeur perçue.", "Pronto para impulsionar sua marca com autoridade?": "Prêt à propulser votre marque avec autorité ?", "Impacto": "Impact", "Quero um Storymaker para o meu próximo evento": "Je veux un Storymaker pour mon prochain événement",
		"Todos os pacotes mensais incluem: Roteiro, Gravação Presencial, Edição completa e Entrega em 3 dias úteis.": "Tous les forfaits mensuels comprennent : scénario, tournage sur place, montage complet et livraison sous 3 jours ouvrés.", "Essencial": "Essentiel", "Crescimento": "Croissance", "Aceleração": "Accélération", "Autoridade": "Autorité", "4 vídeos por mês": "4 vidéos par mois", "6 vídeos por mês": "6 vidéos par mois", "10 vídeos por mês": "10 vidéos par mois", "15 vídeos por mês": "15 vidéos par mois", "Roteiro": "Scénario", "Gravação presencial": "Tournage sur place", "Edição completa": "Montage complet", "Entrega em 3 dias úteis": "Livraison sous 3 jours ouvrés", "Escolher Essencial": "Choisir Essentiel", "Escolher Crescimento": "Choisir Croissance", "Escolher Aceleração": "Choisir Accélération", "Escolher Autoridade": "Choisir Autorité", "O material bruto deve ser enviado previamente para análise técnica.": "Les rushes doivent être envoyés au préalable pour analyse technique.", "60€/vídeo": "60 €/vidéo",
	},
	de: {
		"Não se preocupe com o que dizer, nem como gravar ou editar. A ": "Keine Sorge, was Sie sagen oder wie Sie filmen und schneiden sollen. ", " cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": " kümmert sich um alles und liefert Ihre fertigen Videos innerhalb von 3 Werktagen.", "Estratégia e Roteiro": "Strategie und Drehbuch", "A Gravação (Eu vou até si)": "Dreh (ich komme zu Ihnen)", "A Magia da Edição": "Die Magie des Schnitts", "Vídeos na sua mão": "Videos in Ihren Händen", "Roteiros Estratégicos": "Strategische Drehbücher", "Direção de Gravação": "Drehregie", "Legendas que prendem": "Fesselnde Untertitel", "Som limpo e Imagem tratada": "Klarer Ton und bearbeitetes Bild", "Imagens extra (B-rolls)": "Zusätzliches Bildmaterial (B-Roll)", "Atendimento Direto": "Direkter Support", "Trabalho real, marca forte e conteúdo que sustenta a percepção de valor.": "Echte Arbeit, eine starke Marke und Inhalte, die den wahrgenommenen Wert stärken.", "Pronto para impulsionar sua marca com autoridade?": "Bereit, Ihre Marke mit Autorität zu stärken?", "Impacto": "Wirkung", "Quero um Storymaker para o meu próximo evento": "Ich möchte einen Storymaker für meine nächste Veranstaltung",
		"Todos os pacotes mensais incluem: Roteiro, Gravação Presencial, Edição completa e Entrega em 3 dias úteis.": "Alle Monatspakete enthalten: Drehbuch, Vor-Ort-Dreh, vollständigen Schnitt und Lieferung innerhalb von 3 Werktagen.", "Essencial": "Essential", "Crescimento": "Wachstum", "Aceleração": "Beschleunigung", "Autoridade": "Autorität", "4 vídeos por mês": "4 Videos pro Monat", "6 vídeos por mês": "6 Videos pro Monat", "10 vídeos por mês": "10 Videos pro Monat", "15 vídeos por mês": "15 Videos pro Monat", "Roteiro": "Drehbuch", "Gravação presencial": "Vor-Ort-Dreh", "Edição completa": "Vollständiger Schnitt", "Entrega em 3 dias úteis": "Lieferung innerhalb von 3 Werktagen", "Escolher Essencial": "Essential wählen", "Escolher Crescimento": "Wachstum wählen", "Escolher Aceleração": "Beschleunigung wählen", "Escolher Autoridade": "Autorität wählen", "O material bruto deve ser enviado previamente para análise técnica.": "Rohmaterial muss vorab zur technischen Analyse gesendet werden.", "60€/vídeo": "60 €/Video",
	},
};

const missingPageTranslations = {
	en: {
		"O serviço premium de Storymaker exclusivo para empresários que não podem perder tempo a segurar no telemóvel.": "The premium Storymaker service for business owners who cannot afford to spend time holding a phone.",
		"Se vai dar uma palestra, organizar um evento, participar numa feira ou fazer o lançamento da sua marca, o seu único foco deve ser viver o momento e fazer networking.": "If you are giving a talk, organising an event, attending a trade fair or launching your brand, your only focus should be living the moment and networking.",
		"O resto é comigo. Com o serviço de Storymaker, acompanho-o presencialmente e atuo como a sua sombra estratégica:": "The rest is my job. With the Storymaker service, I accompany you in person and act as your strategic shadow:",
		"Bastidores de uma produção Potencializa": "Behind the scenes of a Potencializa production",
		"Vai realizar ou participar num evento? Seremos os seus olhos ": "Hosting or attending an event? We will be your eyes ", "e a sua câmera": "and your camera",
		"Métricas que comprovam crescimento real.": "Metrics that prove real growth.", "Trabalhamos para gerar resultados mensuráveis com impacto direto no reconhecimento e nas conversões de seus projetos.": "We work to generate measurable results with a direct impact on your projects' recognition and conversions.", "Resultados": "Results", "Impressões mensais alcançadas": "Monthly impressions reached", "Leads qualificados gerados": "Qualified leads generated", "Aumento médio de engajamento": "Average engagement increase", "Crescimento de visibilidade digital": "Digital visibility growth",
		"Serviços Avulsos": "One-off services", "Soluções específicas para fortalecer sua presença digital em cada ponto de contato.": "Specific solutions to strengthen your digital presence at every touchpoint.", "Serviços avulsos pensados para projetos que desejam apoio especializado em design, tráfego, captação e cobertura digital.": "One-off services for projects seeking specialised support in design, paid traffic, content capture and digital coverage.", "Design Gráfico": "Graphic design", "Gestão de Tráfego": "Paid traffic management", "Captação": "Lead generation", "Cobertura Digital": "Digital coverage",
		"Se já grava os seus próprios vídeos e quer apenas a nossa edição premium, fazemos edições unitárias por 60€/vídeo.": "If you record your own videos and only need our premium editing, we offer individual edits for EUR 60/video.",
	},
	es: {
		"O serviço premium de Storymaker exclusivo para empresários que não podem perder tempo a segurar no telemóvel.": "El servicio premium de Storymaker para empresarios que no pueden perder tiempo sujetando el móvil.", "Se vai dar uma palestra, organizar um evento, participar numa feira ou fazer o lançamento da sua marca, o seu único foco deve ser viver o momento e fazer networking.": "Si vas a dar una charla, organizar un evento, participar en una feria o lanzar tu marca, tu único objetivo debe ser vivir el momento y hacer networking.", "O resto é comigo. Com o serviço de Storymaker, acompanho-o presencialmente e atuo como a sua sombra estratégica:": "El resto es cosa mía. Con el servicio de Storymaker, te acompaño en persona y actúo como tu sombra estratégica:", "Bastidores de uma produção Potencializa": "Detrás de cámaras de una producción Potencializa", "Vai realizar ou participar num evento? Seremos os seus olhos ": "¿Vas a organizar o participar en un evento? Seremos tus ojos ", "e a sua câmera": "y tu cámara", "Métricas que comprovam crescimento real.": "Métricas que demuestran un crecimiento real.", "Trabalhamos para gerar resultados mensuráveis com impacto direto no reconhecimento e nas conversões de seus projetos.": "Trabajamos para generar resultados medibles con impacto directo en el reconocimiento y las conversiones de tus proyectos.", "Resultados": "Resultados", "Impressões mensais alcançadas": "Impresiones mensuales alcanzadas", "Leads qualificados gerados": "Leads cualificados generados", "Aumento médio de engajamento": "Aumento medio del engagement", "Crescimento de visibilidade digital": "Crecimiento de visibilidad digital", "Serviços Avulsos": "Servicios puntuales", "Soluções específicas para fortalecer sua presença digital em cada ponto de contato.": "Soluciones específicas para fortalecer tu presencia digital en cada punto de contacto.", "Serviços avulsos pensados para projetos que desejam apoio especializado em design, tráfego, captação e cobertura digital.": "Servicios puntuales para proyectos que buscan apoyo especializado en diseño, tráfico, captación y cobertura digital.", "Design Gráfico": "Diseño gráfico", "Gestão de Tráfego": "Gestión de tráfico", "Captação": "Captación", "Cobertura Digital": "Cobertura digital", "Se já grava os seus próprios vídeos e quer apenas a nossa edição premium, fazemos edições unitárias por 60€/vídeo.": "Si grabas tus propios vídeos y solo necesitas nuestra edición premium, hacemos ediciones individuales por 60€/vídeo.",
	},
	fr: {
		"O serviço premium de Storymaker exclusivo para empresários que não podem perder tempo a segurar no telemóvel.": "Le service premium de Storymaker pour les entrepreneurs qui ne peuvent pas perdre du temps à tenir un téléphone.", "Se vai dar uma palestra, organizar um evento, participar numa feira ou fazer o lançamento da sua marca, o seu único foco deve ser viver o momento e fazer networking.": "Si vous donnez une conférence, organisez un événement, participez à un salon ou lancez votre marque, votre seul objectif doit être de vivre le moment et de faire du réseautage.", "O resto é comigo. Com o serviço de Storymaker, acompanho-o presencialmente e atuo como a sua sombra estratégica:": "Le reste, c'est mon travail. Avec le service Storymaker, je vous accompagne sur place et agis comme votre ombre stratégique :", "Bastidores de uma produção Potencializa": "Coulisses d'une production Potencializa", "Vai realizar ou participar num evento? Seremos os seus olhos ": "Vous organisez ou participez à un événement ? Nous serons vos yeux ", "e a sua câmera": "et votre caméra", "Métricas que comprovam crescimento real.": "Des indicateurs qui prouvent une croissance réelle.", "Trabalhamos para gerar resultados mensuráveis com impacto direto no reconhecimento e nas conversões de seus projetos.": "Nous travaillons à générer des résultats mesurables qui renforcent la notoriété et les conversions de vos projets.", "Resultados": "Résultats", "Impressões mensais alcançadas": "Impressions mensuelles atteintes", "Leads qualificados gerados": "Prospects qualifiés générés", "Aumento médio de engajamento": "Hausse moyenne de l'engagement", "Crescimento de visibilidade digital": "Croissance de la visibilité numérique", "Serviços Avulsos": "Services ponctuels", "Soluções específicas para fortalecer sua presença digital em cada ponto de contato.": "Des solutions ciblées pour renforcer votre présence numérique à chaque point de contact.", "Serviços avulsos pensados para projetos que desejam apoio especializado em design, tráfego, captação e cobertura digital.": "Des services ponctuels pour les projets qui souhaitent un soutien spécialisé en design, trafic, captation et couverture numérique.", "Design Gráfico": "Design graphique", "Gestão de Tráfego": "Gestion du trafic", "Captação": "Génération de prospects", "Cobertura Digital": "Couverture numérique", "Se já grava os seus próprios vídeos e quer apenas a nossa edição premium, fazemos edições unitárias por 60€/vídeo.": "Si vous filmez vos propres vidéos et avez seulement besoin de notre montage premium, nous proposons des montages à l'unité pour 60 €/vidéo.",
	},
	de: {
		"O serviço premium de Storymaker exclusivo para empresários que não podem perder tempo a segurar no telemóvel.": "Der Premium-Storymaker-Service für Unternehmer, die keine Zeit mit dem Halten eines Telefons verlieren können.", "Se vai dar uma palestra, organizar um evento, participar numa feira ou fazer o lançamento da sua marca, o seu único foco deve ser viver o momento e fazer networking.": "Wenn Sie einen Vortrag halten, eine Veranstaltung organisieren, an einer Messe teilnehmen oder Ihre Marke lancieren, sollte Ihr einziger Fokus auf dem Moment und Networking liegen.", "O resto é comigo. Com o serviço de Storymaker, acompanho-o presencialmente e atuo como a sua sombra estratégica:": "Der Rest ist meine Aufgabe. Mit dem Storymaker-Service begleite ich Sie persönlich und bin Ihr strategischer Schatten:", "Bastidores de uma produção Potencializa": "Hinter den Kulissen einer Potencializa-Produktion", "Vai realizar ou participar num evento? Seremos os seus olhos ": "Veranstalten Sie eine Veranstaltung oder nehmen Sie daran teil? Wir sind Ihre Augen ", "e a sua câmera": "und Ihre Kamera", "Métricas que comprovam crescimento real.": "Kennzahlen, die echtes Wachstum belegen.", "Trabalhamos para gerar resultados mensuráveis com impacto direto no reconhecimento e nas conversões de seus projetos.": "Wir schaffen messbare Ergebnisse mit direktem Einfluss auf Bekanntheit und Conversions Ihrer Projekte.", "Resultados": "Ergebnisse", "Impressões mensais alcançadas": "Erreichte monatliche Impressionen", "Leads qualificados gerados": "Generierte qualifizierte Leads", "Aumento médio de engajamento": "Durchschnittlicher Engagement-Zuwachs", "Crescimento de visibilidade digital": "Wachstum der digitalen Sichtbarkeit", "Serviços Avulsos": "Einzelleistungen", "Soluções específicas para fortalecer sua presença digital em cada ponto de contato.": "Spezifische Lösungen zur Stärkung Ihrer digitalen Präsenz an jedem Kontaktpunkt.", "Serviços avulsos pensados para projetos que desejam apoio especializado em design, tráfego, captação e cobertura digital.": "Einzelleistungen für Projekte mit Bedarf an spezialisierter Unterstützung in Design, Traffic, Erfassung und digitaler Berichterstattung.", "Design Gráfico": "Grafikdesign", "Gestão de Tráfego": "Traffic-Management", "Captação": "Leadgenerierung", "Cobertura Digital": "Digitale Berichterstattung", "Se já grava os seus próprios vídeos e quer apenas a nossa edição premium, fazemos edições unitárias por 60€/vídeo.": "Wenn Sie Ihre Videos selbst aufnehmen und nur unseren Premium-Schnitt benötigen, bieten wir Einzelschnitte für 60 EUR pro Video an.",
	},
};

const authorityTranslations = {
	en: {
		"Mais de 6 anos a transformar ideias em vídeos que vendem.": "Over 6 years transforming ideas into videos that sell.", "Fundadora da Potencializa": "Potencializa founder", "Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "I am passionate about what I do. Brazilian and naturally creative, with one obsession: making your videos hold attention from the first second to the last.", "Ao longo de ": "Over ", "6 anos no mercado audiovisual": "6 years in the audiovisual industry", ", já editei milhares de vídeos. Prestei serviço para mais de ": ", I have edited thousands of videos. I have served more than ", "50 empresas": "50 companies", " de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": " across dozens of different niches, from Rio de Janeiro to Portugal.", "Não sou “apenas uma editora”. Sou formada em Marketing e especializada em ": "I am not just an editor. I have a degree in Marketing and specialise in ", "Criação de Roteiros e Formatos Virais": "creating scripts and viral formats", ". Além disso, a minha base no ": ". In addition, my foundation in ", "Marketing Político": "Political Marketing", " foi forjada na prática: trabalhei ": " was forged through practice: I spent ", "4 anos intensos ao lado de um vereador (que foi reeleito)": "4 intense years working alongside a city councillor who was re-elected", ". A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ": ". Politics allows no delays or lack of ideas, and this experience made me an extremely ", "ágil, criativa e habituada a entregar excelência sob pressão": "agile, creative professional accustomed to delivering excellence under pressure", "Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "This means every script I write and every cut I make has a clear purpose: to create desire, retention and authority for you.", "Além de aplicar tudo isso nos meus clientes, já ": "Besides applying all this to my clients, I have already ", "formei mais de 50 alunos": "trained more than 50 students", ", ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": ", teaching the art of creating videos that deliver results. I study and improve every day, ensuring my clients are always one step ahead in digital.", "Quero trabalhar com a Potencializa": "I want to work with Potencializa",
	},
	es: {
		"Mais de 6 anos a transformar ideias em vídeos que vendem.": "Más de 6 años transformando ideas en vídeos que venden.", "Fundadora da Potencializa": "Fundadora de Potencializa", "Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "Me apasiona lo que hago. Brasileña y creativa por naturaleza, con una obsesión: hacer que tus vídeos mantengan la atención de principio a fin.", "Ao longo de ": "A lo largo de ", "6 anos no mercado audiovisual": "6 años en el mercado audiovisual", ", já editei milhares de vídeos. Prestei serviço para mais de ": ", ya he editado miles de vídeos. He trabajado para más de ", "50 empresas": "50 empresas", " de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": " de decenas de sectores, desde Río de Janeiro hasta Portugal.", "Não sou “apenas uma editora”. Sou formada em Marketing e especializada em ": "No soy solo editora. Soy licenciada en Marketing y estoy especializada en ", "Criação de Roteiros e Formatos Virais": "creación de guiones y formatos virales", ". Além disso, a minha base no ": ". Además, mi base en ", "Marketing Político": "Marketing Político", " foi forjada na prática: trabalhei ": " se forjó en la práctica: trabajé ", "4 anos intensos ao lado de um vereador (que foi reeleito)": "4 años intensos junto a un concejal que fue reelegido", ". A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ": ". La política no permite retrasos ni falta de ideas, y esta experiencia me convirtió en una profesional extremadamente ", "ágil, criativa e habituada a entregar excelência sob pressão": "ágil, creativa y acostumbrada a ofrecer excelencia bajo presión", "Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "Esto significa que cada guion y cada corte tienen un objetivo claro: generar deseo, retención y autoridad para ti.", "Além de aplicar tudo isso nos meus clientes, já ": "Además de aplicar todo esto con mis clientes, ya he ", "formei mais de 50 alunos": "formado a más de 50 alumnos", ", ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": ", enseñando el arte de crear vídeos que dan resultados. Estudio y mejoro cada día para que mis clientes estén siempre un paso por delante en lo digital.", "Quero trabalhar com a Potencializa": "Quiero trabajar con Potencializa",
	},
	fr: {
		"Mais de 6 anos a transformar ideias em vídeos que vendem.": "Plus de 6 ans à transformer des idées en vidéos qui vendent.", "Fundadora da Potencializa": "Fondatrice de Potencializa", "Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "Je suis passionnée par mon travail. Brésilienne et naturellement créative, j'ai une obsession : retenir l'attention du premier au dernier instant.", "Ao longo de ": "En ", "6 anos no mercado audiovisual": "6 ans dans le secteur audiovisuel", ", já editei milhares de vídeos. Prestei serviço para mais de ": ", j'ai monté des milliers de vidéos et travaillé pour plus de ", "50 empresas": "50 entreprises", " de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": " dans des dizaines de secteurs, de Rio de Janeiro jusqu'au Portugal.", "Não sou “apenas uma editora”. Sou formada em Marketing e especializada em ": "Je ne suis pas qu'une monteuse. Diplômée en marketing, je suis spécialisée dans la ", "Criação de Roteiros e Formatos Virais": "création de scénarios et de formats viraux", ". Além disso, a minha base no ": ". Ma base en ", "Marketing Político": "marketing politique", " foi forjada na prática: trabalhei ": " s'est forgée dans la pratique : j'ai travaillé ", "4 anos intensos ao lado de um vereador (que foi reeleito)": "4 années intenses aux côtés d'un conseiller municipal réélu", ". A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ": ". La politique ne permet ni retard ni manque d'idées et cette expérience a fait de moi une professionnelle extrêmement ", "ágil, criativa e habituada a entregar excelência sob pressão": "agile, créative et habituée à viser l'excellence sous pression", "Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "Chaque scénario et chaque coupe ont donc un objectif clair : créer du désir, de la rétention et de l'autorité pour vous.", "Além de aplicar tudo isso nos meus clientes, já ": "En plus d'appliquer tout cela à mes clients, j'ai déjà ", "formei mais de 50 alunos": "formé plus de 50 élèves", ", ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": ", en leur enseignant l'art de créer des vidéos efficaces. J'étudie et me perfectionne chaque jour pour que mes clients gardent une longueur d'avance dans le numérique.", "Quero trabalhar com a Potencializa": "Je veux travailler avec Potencializa",
	},
	de: {
		"Mais de 6 anos a transformar ideias em vídeos que vendem.": "Seit über 6 Jahren verwandle ich Ideen in Videos, die verkaufen.", "Fundadora da Potencializa": "Gründerin von Potencializa", "Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "Ich liebe, was ich tue. Als Brasilianerin bin ich von Natur aus kreativ und habe eine Leidenschaft: Ihre Videos vom ersten bis zum letzten Moment fesselnd zu machen.", "Ao longo de ": "In ", "6 anos no mercado audiovisual": "6 Jahren in der audiovisuellen Branche", ", já editei milhares de vídeos. Prestei serviço para mais de ": ", habe ich Tausende Videos geschnitten und für mehr als ", "50 empresas": "50 Unternehmen", " de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": " aus dutzenden Branchen gearbeitet, von Rio de Janeiro bis Portugal.", "Não sou “apenas uma editora”. Sou formada em Marketing e especializada em ": "Ich bin nicht nur Cutterin. Ich habe Marketing studiert und bin spezialisiert auf ", "Criação de Roteiros e Formatos Virais": "Skripterstellung und virale Formate", ". Além disso, a minha base no ": ". Meine Grundlage im ", "Marketing Político": "politischen Marketing", " foi forjada na prática: trabalhei ": " entstand in der Praxis: Ich arbeitete ", "4 anos intensos ao lado de um vereador (que foi reeleito)": "4 intensive Jahre an der Seite eines wiedergewählten Stadtrats", ". A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ": ". Die Politik duldet weder Verzögerungen noch Ideenmangel und machte mich zu einer äußerst ", "ágil, criativa e habituada a entregar excelência sob pressão": "agilen, kreativen Expertin, die unter Druck hervorragende Ergebnisse liefert", "Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "Jedes Skript und jeder Schnitt verfolgt ein klares Ziel: Begehren, Bindung und Autorität für Sie zu schaffen.", "Além de aplicar tudo isso nos meus clientes, já ": "Neben der Anwendung bei meinen Kunden habe ich bereits ", "formei mais de 50 alunos": "mehr als 50 Schüler ausgebildet", ", ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": ", denen ich die Kunst wirkungsvoller Videos beibringe. Ich lerne und verbessere mich täglich, damit meine Kunden der digitalen Entwicklung stets voraus sind.", "Quero trabalhar com a Potencializa": "Ich möchte mit Potencializa arbeiten",
	},
};

Object.assign(authorityTranslations.en, {
	"Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "I am passionate about what I do. Brazilian and naturally creative, with one obsession: making your videos hold attention from the first second to the last.",
	"Ao longo de 6 anos no mercado audiovisual, já editei milhares de vídeos. Prestei serviço para mais de 50 empresas de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": "Over 6 years in the audiovisual industry, I have edited thousands of videos. I have worked for more than 50 companies across dozens of different niches, from Rio de Janeiro to Portugal.",
	"Não sou “apenas uma editora”. Sou formada em Marketing e especializada em Criação de Roteiros e Formatos Virais. Além disso, a minha base no Marketing Político foi forjada na prática: trabalhei 4 anos intensos ao lado de um vereador (que foi reeleito). A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ágil, criativa e habituada a entregar excelência sob pressão.": "I am not just an editor. I have a degree in Marketing and specialise in scriptwriting and viral formats. My foundation in Political Marketing was forged through practice: I spent 4 intense years working alongside a city councillor who was re-elected. Politics allows no delays or lack of ideas, and this experience made me an agile, creative professional accustomed to delivering excellence under pressure.",
	"Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "This means every script I write and every cut I make has a clear purpose: to create desire, retention and authority for you.",
	"Além de aplicar tudo isso nos meus clientes, já formei mais de 50 alunos, ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": "Besides applying all this to my clients, I have trained more than 50 students, teaching the art of creating videos that deliver results. I study and improve every day, ensuring my clients are always one step ahead in digital.",
});
Object.assign(authorityTranslations.es, {
	"Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "Me apasiona lo que hago. Brasileña y creativa por naturaleza, con una obsesión: hacer que tus vídeos mantengan la atención del primer al último segundo.", "Ao longo de 6 anos no mercado audiovisual, já editei milhares de vídeos. Prestei serviço para mais de 50 empresas de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": "Durante 6 años en el sector audiovisual, he editado miles de vídeos. He trabajado para más de 50 empresas de decenas de sectores, desde Río de Janeiro hasta Portugal.", "Não sou “apenas uma editora”. Sou formada em Marketing e especializada em Criação de Roteiros e Formatos Virais. Além disso, a minha base no Marketing Político foi forjada na prática: trabalhei 4 anos intensos ao lado de um vereador (que foi reeleito). A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ágil, criativa e habituada a entregar excelência sob pressão.": "No soy solo editora. Soy licenciada en Marketing y especialista en creación de guiones y formatos virales. Mi base en Marketing Político se forjó en la práctica: trabajé 4 años intensos junto a un concejal que fue reelegido. La política no permite retrasos ni falta de ideas, y esta experiencia me convirtió en una profesional ágil, creativa y acostumbrada a ofrecer excelencia bajo presión.", "Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "Esto significa que cada guion y cada corte tienen un objetivo claro: generar deseo, retención y autoridad para ti.", "Além de aplicar tudo isso nos meus clientes, já formei mais de 50 alunos, ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": "Además de aplicar todo esto con mis clientes, he formado a más de 50 alumnos, enseñando el arte de crear vídeos que dan resultados. Estudio y mejoro cada día para que mis clientes estén siempre un paso por delante en lo digital.",
});
Object.assign(authorityTranslations.fr, {
	"Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "Je suis passionnée par mon travail. Brésilienne et naturellement créative, j'ai une obsession : retenir l'attention du premier au dernier instant.", "Ao longo de 6 anos no mercado audiovisual, já editei milhares de vídeos. Prestei serviço para mais de 50 empresas de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": "En 6 ans dans le secteur audiovisuel, j'ai monté des milliers de vidéos. J'ai travaillé pour plus de 50 entreprises dans des dizaines de secteurs, de Rio de Janeiro jusqu'au Portugal.", "Não sou “apenas uma editora”. Sou formada em Marketing e especializada em Criação de Roteiros e Formatos Virais. Além disso, a minha base no Marketing Político foi forjada na prática: trabalhei 4 anos intensos ao lado de um vereador (que foi reeleito). A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ágil, criativa e habituada a entregar excelência sob pressão.": "Je ne suis pas qu'une monteuse. Diplômée en marketing, je suis spécialisée dans la création de scénarios et de formats viraux. Ma base en marketing politique s'est forgée dans la pratique : j'ai travaillé 4 années intenses aux côtés d'un conseiller municipal réélu. La politique ne tolère ni retard ni manque d'idées, et cette expérience a fait de moi une professionnelle agile, créative et habituée à viser l'excellence sous pression.", "Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "Chaque scénario et chaque coupe ont donc un objectif clair : créer du désir, de la rétention et de l'autorité pour vous.", "Além de aplicar tudo isso nos meus clientes, já formei mais de 50 alunos, ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": "En plus d'appliquer tout cela à mes clients, j'ai formé plus de 50 élèves en leur enseignant l'art de créer des vidéos efficaces. J'étudie et me perfectionne chaque jour pour que mes clients gardent une longueur d'avance dans le numérique.",
});
Object.assign(authorityTranslations.de, {
	"Sou apaixonada pelo que faço. Brasileira, criativa por natureza, e com uma obsessão: fazer os seus vídeos prenderem a atenção do primeiro ao último segundo.": "Ich liebe, was ich tue. Als Brasilianerin bin ich von Natur aus kreativ und habe eine Leidenschaft: Ihre Videos vom ersten bis zum letzten Moment fesselnd zu machen.", "Ao longo de 6 anos no mercado audiovisual, já editei milhares de vídeos. Prestei serviço para mais de 50 empresas de dezenas de nichos diferentes, desde o Rio de Janeiro até aqui em Portugal.": "In 6 Jahren in der audiovisuellen Branche habe ich Tausende Videos geschnitten und für mehr als 50 Unternehmen aus dutzenden Branchen gearbeitet, von Rio de Janeiro bis Portugal.", "Não sou “apenas uma editora”. Sou formada em Marketing e especializada em Criação de Roteiros e Formatos Virais. Além disso, a minha base no Marketing Político foi forjada na prática: trabalhei 4 anos intensos ao lado de um vereador (que foi reeleito). A dinâmica da política não permite atrasos nem falta de ideias, e essa experiência transformou-me numa profissional extremamente ágil, criativa e habituada a entregar excelência sob pressão.": "Ich bin nicht nur Cutterin. Ich habe Marketing studiert und bin auf Skripterstellung und virale Formate spezialisiert. Meine Grundlage im politischen Marketing entstand in der Praxis: Ich arbeitete 4 intensive Jahre an der Seite eines wiedergewählten Stadtrats. Die Politik duldet weder Verzögerungen noch Ideenmangel und machte mich zu einer agilen, kreativen Expertin, die unter Druck hervorragende Ergebnisse liefert.", "Isso significa que cada roteiro que escrevo e cada corte que faço tem uma intenção clara: gerar desejo, retenção e autoridade para si.": "Jedes Skript und jeder Schnitt verfolgt ein klares Ziel: Begehren, Bindung und Autorität für Sie zu schaffen.", "Além de aplicar tudo isso nos meus clientes, já formei mais de 50 alunos, ensinando a arte de criar vídeos que dão resultados. Estou a estudar e a aprimorar-me todos os dias, garantindo que os meus clientes estão sempre um passo à frente no digital.": "Neben der Anwendung bei meinen Kunden habe ich mehr als 50 Schüler ausgebildet und ihnen die Kunst wirkungsvoller Videos beigebracht. Ich lerne und verbessere mich täglich, damit meine Kunden der digitalen Entwicklung stets voraus sind.",
});

Object.assign(translations.en, {
	"Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de Impacto": "Connect with our team of experts and accelerate conversions with smart campaigns and impactful content.", "Precisa apenas da edição?": "Only need editing?", "Quero apenas o serviço de edição": "I only want the editing service", "Escolha o plano ideal para a sua estratégia de conteúdo.": "Choose the ideal plan for your content strategy.",
});
Object.assign(translations.es, {
	"Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de Impacto": "Conecta con nuestro equipo de especialistas y acelera las conversiones con campañas inteligentes y contenido de impacto.", "Precisa apenas da edição?": "¿Solo necesitas la edición?", "Quero apenas o serviço de edição": "Solo quiero el servicio de edición", "Escolha o plano ideal para a sua estratégia de conteúdo.": "Elige el plan ideal para tu estrategia de contenidos.",
});
Object.assign(translations.fr, {
	"Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de Impacto": "Connectez-vous à notre équipe d'experts et accélérez les conversions grâce à des campagnes intelligentes et à un contenu à impact.", "Precisa apenas da edição?": "Vous avez seulement besoin du montage ?", "Quero apenas o serviço de edição": "Je veux uniquement le service de montage", "Escolha o plano ideal para a sua estratégia de conteúdo.": "Choisissez le forfait idéal pour votre stratégie de contenu.",
});
Object.assign(translations.de, {
	"Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de Impacto": "Vernetzen Sie sich mit unserem Expertenteam und steigern Sie Conversions mit intelligenten Kampagnen und wirkungsvollen Inhalten.", "Precisa apenas da edição?": "Benötigen Sie nur den Schnitt?", "Quero apenas o serviço de edição": "Ich möchte nur den Schnittservice", "Escolha o plano ideal para a sua estratégia de conteúdo.": "Wählen Sie das ideale Paket für Ihre Content-Strategie.",
});

const reportedTranslations = {
	en: {
		"Produção de Vídeos": "Video production", "Storymaker": "Storymaker", "Não se preocupe com o que dizer, nem como gravar ou editar. A Potencializa cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": "Don't worry about what to say, how to film or edit. Potencializa takes care of everything and delivers your finished videos within 3 business days.", "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "Hosting or attending an event? We will be your eyes and your camera", "Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de ": "Connect with our team of experts and accelerate conversions with smart campaigns and content with ", "Fechar modal de contato": "Close contact modal", "Preencha seus dados para iniciar o contato via WhatsApp.": "Fill in your details to start the conversation via WhatsApp.",
		"1. Eu tenho vergonha das câmaras. Vai funcionar para mim?": "1. I feel embarrassed in front of cameras. Will this work for me?", "Sim! Esse é exatamente o meu diferencial. Ao ir gravar presencialmente consigo, eu faço a direção de cena. Ajudo-o a relaxar, indico a postura certa, o tom de voz e gravamos por partes. Não precisa de decorar nada, estou lá para facilitar tudo.": "Yes! That is exactly my advantage. When I film you in person, I direct the scene, help you relax, guide your posture and tone of voice, and we record in sections. You do not need to memorise anything.", "2. Onde são feitas as gravações?": "2. Where are the recordings made?", "As gravações são feitas no seu espaço (clínica, escritório, loja, casa). Eu desloco-me até ao seu ambiente de trabalho para que o vídeo passe o máximo de autoridade e reflita a sua marca real.": "Recordings take place at your location (clinic, office, shop or home). I come to your workplace so the video conveys authority and reflects your real brand.", "3. Vocês criam mesmo o que eu vou dizer?": "3. Do you really create what I will say?", "Sim. Graças à minha formação em marketing e guiões virais, eu estudo o seu nicho e levo os roteiros totalmente prontos para o dia da gravação. Você apenas lê, aprova e gravamos.": "Yes. Thanks to my training in marketing and viral scripts, I study your niche and bring the scripts ready for filming. You just read, approve and record.", "4. E se eu já gravar sozinho e quiser apenas a edição?": "4. What if I record myself and only want editing?", "Também fazemos! O valor para vídeos unitários (apenas edição) é de 60€. Basta enviar o material bruto antes para eu analisar a viabilidade e garantir o padrão Potencializa de qualidade.": "We do that too! Individual videos with editing only cost EUR 60. Send the raw material beforehand so I can assess it and ensure Potencializa's quality standard.", "5. Em quanto tempo recebo os vídeos prontos?": "5. How long does it take to receive the finished videos?", "Após o dia da nossa gravação, entrego os vídeos 100% editados e prontos a publicar num prazo máximo de 3 dias úteis.": "After our filming day, I deliver the videos fully edited and ready to publish within a maximum of 3 business days.", "6. E se eu não gostar de algum detalhe da edição?": "6. What if I do not like a detail of the editing?", "Sem problema. O meu objetivo é que o vídeo fique perfeito e com a identidade da sua marca. Tem direito a pedir ajustes pontuais até ficar 100% satisfeito.": "No problem. My goal is a perfect video aligned with your brand identity. You can request specific adjustments until you are completely satisfied.",
	},
	es: {
		"Produção de Vídeos": "Producción de vídeos", "Storymaker": "Storymaker", "Não se preocupe com o que dizer, nem como gravar ou editar. A Potencializa cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": "No te preocupes por qué decir ni por cómo grabar o editar. Potencializa se encarga de todo y entrega tus vídeos listos en un máximo de 3 días laborables.", "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "¿Vas a organizar o participar en un evento? Seremos tus ojos y tu cámara", "Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de ": "Conecta con nuestro equipo de especialistas y acelera las conversiones con campañas inteligentes y contenido de ", "Fechar modal de contato": "Cerrar modal de contacto", "Preencha seus dados para iniciar o contato via WhatsApp.": "Completa tus datos para iniciar el contacto por WhatsApp.",
		"1. Eu tenho vergonha das câmaras. Vai funcionar para mim?": "1. Me da vergüenza estar ante las cámaras. ¿Funcionará para mí?", "Sim! Esse é exatamente o meu diferencial. Ao ir gravar presencialmente consigo, eu faço a direção de cena. Ajudo-o a relaxar, indico a postura certa, o tom de voz e gravamos por partes. Não precisa de decorar nada, estou lá para facilitar tudo.": "¡Sí! Ese es precisamente mi diferencial. Cuando grabo contigo en persona, dirijo la escena, te ayudo a relajarte y te guío con la postura y el tono de voz. Grabamos por partes y no tienes que memorizar nada.", "2. Onde são feitas as gravações?": "2. ¿Dónde se hacen las grabaciones?", "As gravações são feitas no seu espaço (clínica, escritório, loja, casa). Eu desloco-me até ao seu ambiente de trabalho para que o vídeo passe o máximo de autoridade e reflita a sua marca real.": "Las grabaciones se hacen en tu espacio (clínica, oficina, tienda o casa). Voy hasta tu lugar de trabajo para que el vídeo transmita autoridad y refleje tu marca real.", "3. Vocês criam mesmo o que eu vou dizer?": "3. ¿Crean realmente lo que voy a decir?", "Sim. Graças à minha formação em marketing e guiões virais, eu estudo o seu nicho e levo os roteiros totalmente prontos para o dia da gravação. Você apenas lê, aprova e gravamos.": "Sí. Estudio tu sector y preparo los guiones gracias a mi formación en marketing y guiones virales. Tú solo lees, apruebas y grabamos.", "4. E se eu já gravar sozinho e quiser apenas a edição?": "4. ¿Y si ya grabo solo y solo quiero la edición?", "Também fazemos! O valor para vídeos unitários (apenas edição) é de 60€. Basta enviar o material bruto antes para eu analisar a viabilidade e garantir o padrão Potencializa de qualidade.": "¡También lo hacemos! La edición de vídeos individuales cuesta 60 €. Envíame el material bruto para evaluar su viabilidad y garantizar el estándar de calidad de Potencializa.", "5. Em quanto tempo recebo os vídeos prontos?": "5. ¿Cuándo recibo los vídeos terminados?", "Após o dia da nossa gravação, entrego os vídeos 100% editados e prontos a publicar num prazo máximo de 3 dias úteis.": "Después de la grabación, entrego los vídeos totalmente editados y listos para publicar en un máximo de 3 días laborables.", "6. E se eu não gostar de algum detalhe da edição?": "6. ¿Y si no me gusta algún detalle de la edición?", "Sem problema. O meu objetivo é que o vídeo fique perfeito e com a identidade da sua marca. Tem direito a pedir ajustes pontuais até ficar 100% satisfeito.": "No hay problema. Mi objetivo es que el vídeo sea perfecto y refleje tu marca. Puedes pedir ajustes puntuales hasta quedar completamente satisfecho.",
	},
	fr: {
		"Produção de Vídeos": "Production vidéo", "Storymaker": "Storymaker", "Não se preocupe com o que dizer, nem como gravar ou editar. A Potencializa cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": "Ne vous inquiétez pas de quoi dire, ni de comment filmer ou monter. Potencializa s'occupe de tout et livre vos vidéos sous 3 jours ouvrés.", "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "Vous organisez ou participez à un événement ? Nous serons vos yeux et votre caméra", "Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de ": "Connectez-vous à notre équipe d'experts et accélérez les conversions grâce à des campagnes intelligentes et du contenu à ", "Fechar modal de contato": "Fermer la fenêtre de contact", "Preencha seus dados para iniciar o contato via WhatsApp.": "Remplissez vos informations pour commencer le contact via WhatsApp.",
		"1. Eu tenho vergonha das câmaras. Vai funcionar para mim?": "1. Je suis gêné devant les caméras. Est-ce que cela fonctionnera pour moi ?", "Sim! Esse é exatamente o meu diferencial. Ao ir gravar presencialmente consigo, eu faço a direção de cena. Ajudo-o a relaxar, indico a postura certa, o tom de voz e gravamos por partes. Não precisa de decorar nada, estou lá para facilitar tudo.": "Oui ! C'est précisément mon avantage. Je dirige la scène sur place, vous aide à vous détendre et vous guide pour la posture et le ton de voix. Nous filmons par séquences, sans rien à mémoriser.", "2. Onde são feitas as gravações?": "2. Où les tournages sont-ils réalisés ?", "As gravações são feitas no seu espaço (clínica, escritório, loja, casa). Eu desloco-me até ao seu ambiente de trabalho para que o vídeo passe o máximo de autoridade e reflita a sua marca real.": "Les tournages ont lieu dans votre espace (clinique, bureau, magasin ou domicile). Je viens sur votre lieu de travail afin que la vidéo reflète votre vraie marque avec autorité.", "3. Vocês criam mesmo o que eu vou dizer?": "3. Créez-vous vraiment ce que je vais dire ?", "Sim. Graças à minha formação em marketing e guiões virais, eu estudo o seu nicho e levo os roteiros totalmente prontos para o dia da gravação. Você apenas lê, aprova e gravamos.": "Oui. J'étudie votre secteur et prépare les scénarios grâce à ma formation en marketing et en scénarios viraux. Vous lisez, approuvez et nous filmons.", "4. E se eu já gravar sozinho e quiser apenas a edição?": "4. Et si je filme seul et souhaite uniquement le montage ?", "Também fazemos! O valor para vídeos unitários (apenas edição) é de 60€. Basta enviar o material bruto antes para eu analisar a viabilidade e garantir o padrão Potencializa de qualidade.": "Nous le faisons aussi ! Le montage seul coûte 60 € par vidéo. Envoyez les rushes afin que j'en vérifie la faisabilité et la qualité.", "5. Em quanto tempo recebo os vídeos prontos?": "5. Quand recevrai-je les vidéos terminées ?", "Após o dia da nossa gravação, entrego os vídeos 100% editados e prontos a publicar num prazo máximo de 3 dias úteis.": "Après le tournage, je livre les vidéos entièrement montées et prêtes à publier sous 3 jours ouvrés maximum.", "6. E se eu não gostar de algum detalhe da edição?": "6. Et si un détail du montage ne me plaît pas ?", "Sem problema. O meu objetivo é que o vídeo fique perfeito e com a identidade da sua marca. Tem direito a pedir ajustes pontuais até ficar 100% satisfeito.": "Aucun problème. Mon objectif est une vidéo parfaite et fidèle à votre identité. Vous pouvez demander des ajustements ciblés jusqu'à satisfaction complète.",
	},
	de: {
		"Produção de Vídeos": "Videoproduktion", "Storymaker": "Storymaker", "Não se preocupe com o que dizer, nem como gravar ou editar. A Potencializa cuida de tudo e entrega os seus vídeos prontos em até 3 dias úteis.": "Keine Sorge, was Sie sagen oder wie Sie filmen und schneiden sollen. Potencializa kümmert sich um alles und liefert Ihre fertigen Videos innerhalb von 3 Werktagen.", "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "Veranstalten Sie ein Event oder nehmen Sie daran teil? Wir sind Ihre Augen und Ihre Kamera", "Conecte-se com nosso time de especialistas e acelere conversões com campanhas inteligentes e conteúdo de ": "Vernetzen Sie sich mit unserem Expertenteam und steigern Sie Conversions mit intelligenten Kampagnen und Inhalten mit ", "Fechar modal de contato": "Kontaktfenster schließen", "Preencha seus dados para iniciar o contato via WhatsApp.": "Füllen Sie Ihre Daten aus, um den Kontakt über WhatsApp zu beginnen.",
		"1. Eu tenho vergonha das câmaras. Vai funcionar para mim?": "1. Ich bin vor der Kamera unsicher. Funktioniert das für mich?", "Sim! Esse é exatamente o meu diferencial. Ao ir gravar presencialmente consigo, eu faço a direção de cena. Ajudo-o a relaxar, indico a postura certa, o tom de voz e gravamos por partes. Não precisa de decorar nada, estou lá para facilitar tudo.": "Ja! Genau das ist mein Vorteil. Beim Dreh vor Ort führe ich Sie durch die Szene, helfe Ihnen zu entspannen und zeige Ihnen Haltung und Tonfall. Wir filmen in Abschnitten, Sie müssen nichts auswendig lernen.", "2. Onde são feitas as gravações?": "2. Wo finden die Aufnahmen statt?", "As gravações são feitas no seu espaço (clínica, escritório, loja, casa). Eu desloco-me até ao seu ambiente de trabalho para que o vídeo passe o máximo de autoridade e reflita a sua marca real.": "Die Aufnahmen finden bei Ihnen statt (Klinik, Büro, Geschäft oder zu Hause). Ich komme zu Ihrem Arbeitsplatz, damit das Video Ihre echte Marke authentisch und souverän zeigt.", "3. Vocês criam mesmo o que eu vou dizer?": "3. Erstellen Sie wirklich, was ich sagen werde?", "Sim. Graças à minha formação em marketing e guiões virais, eu estudo o seu nicho e levo os roteiros totalmente prontos para o dia da gravação. Você apenas lê, aprova e gravamos.": "Ja. Ich analysiere Ihre Branche und bringe dank meiner Ausbildung in Marketing und viralen Skripten fertige Texte zum Dreh mit. Sie lesen, bestätigen und wir filmen.", "4. E se eu já gravar sozinho e quiser apenas a edição?": "4. Was ist, wenn ich selbst aufnehme und nur den Schnitt möchte?", "Também fazemos! O valor para vídeos unitários (apenas edição) é de 60€. Basta enviar o material bruto antes para eu analisar a viabilidade e garantir o padrão Potencializa de qualidade.": "Das bieten wir ebenfalls an! Einzelschnitt kostet 60 € pro Video. Senden Sie das Rohmaterial vorab, damit ich die Umsetzbarkeit und den Qualitätsstandard prüfen kann.", "5. Em quanto tempo recebo os vídeos prontos?": "5. Wie schnell erhalte ich die fertigen Videos?", "Após o dia da nossa gravação, entrego os vídeos 100% editados e prontos a publicar num prazo máximo de 3 dias úteis.": "Nach dem Drehtag liefere ich die vollständig bearbeiteten und veröffentlichungsfertigen Videos innerhalb von maximal 3 Werktagen.", "6. E se eu não gostar de algum detalhe da edição?": "6. Was, wenn mir ein Detail des Schnitts nicht gefällt?", "Sem problema. O meu objetivo é que o vídeo fique perfeito e com a identidade da sua marca. Tem direito a pedir ajustes pontuais até ficar 100% satisfeito.": "Kein Problem. Mein Ziel ist ein perfektes Video im Stil Ihrer Marke. Sie können gezielte Anpassungen anfordern, bis Sie vollständig zufrieden sind.",
	},
};

Object.assign(reportedTranslations.en, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "Hosting or attending an event? We will be your eyes ", "e a sua câmera": "and your camera", "Impacto": "Impact",
});
Object.assign(reportedTranslations.es, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "¿Vas a organizar o participar en un evento? Seremos tus ojos ", "e a sua câmera": "y tu cámara", "Impacto": "Impacto",
});
Object.assign(reportedTranslations.fr, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "Vous organisez ou participez à un événement ? Nous serons vos yeux ", "e a sua câmera": "et votre caméra", "Impacto": "Impact",
});
Object.assign(reportedTranslations.de, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "Veranstalten Sie eine Veranstaltung oder nehmen Sie daran teil? Wir sind Ihre Augen ", "e a sua câmera": "und Ihre Kamera", "Impacto": "Wirkung",
});

Object.assign(translations.en, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "Hosting or attending an event? We will be your eyes ", "e a sua câmera": "and your camera", "Impacto": "Impact",
});
Object.assign(translations.es, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "¿Vas a organizar o participar en un evento? Seremos tus ojos ", "e a sua câmera": "y tu cámara", "Impacto": "Impacto",
});
Object.assign(translations.fr, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "Vous organisez ou participez à un événement ? Nous serons vos yeux ", "e a sua câmera": "et votre caméra", "Impacto": "Impact",
});
Object.assign(translations.de, {
	"Vai realizar ou participar num evento? Seremos os seus olhos ": "Veranstalten Sie eine Veranstaltung oder nehmen Sie daran teil? Wir sind Ihre Augen ", "e a sua câmera": "und Ihre Kamera", "Impacto": "Wirkung",
});

Object.assign(translations.en, { "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "Hosting or attending an event? We will be your eyes and your camera" });
Object.assign(translations.es, { "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "¿Vas a organizar o participar en un evento? Seremos tus ojos y tu cámara" });
Object.assign(translations.fr, { "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "Vous organisez ou participez à un événement ? Nous serons vos yeux et votre caméra" });
Object.assign(translations.de, { "Vai realizar ou participar num evento? Seremos os seus olhos e a sua câmera": "Veranstalten Sie ein Event oder nehmen Sie daran teil? Wir sind Ihre Augen und Ihre Kamera" });

const benefitsTranslations = {
	en: {
		"Fim do bloqueio criativo:": "End creative block:", "Não sabe o que gravar? Eu tenho formações em marketing e formatos virais. Crio os guiões e roteiros exatos para o seu nicho.": "Do not know what to record? I am trained in marketing and viral formats. I create the exact scripts for your niche.", "Gravação sem stress:": "Stress-free filming:", "Nada de tentar equilibrar o telemóvel na janela. Eu vou até si com o olhar clínico de quem já gravou dezenas de nichos diferentes e dirijo a sua gravação.": "No more balancing your phone on a window. I come to you with the trained eye of someone who has filmed dozens of different niches and direct your shoot.", "Qualidade que vende:": "Quality that sells:", "Legendas magnéticas, cortes precisos, som limpo e imagem profissional. O seu conteúdo vai destacar-se da concorrência e prender a atenção logo nos primeiros 3 segundos.": "Magnetic captions, precise cuts, clean sound and a professional image. Your content will stand out from the competition and capture attention in the first 3 seconds.",
	},
	es: {
		"Fim do bloqueio criativo:": "Fin del bloqueo creativo:", "Não sabe o que gravar? Eu tenho formações em marketing e formatos virais. Crio os guiões e roteiros exatos para o seu nicho.": "¿No sabes qué grabar? Tengo formación en marketing y formatos virales. Creo los guiones exactos para tu sector.", "Gravação sem stress:": "Grabación sin estrés:", "Nada de tentar equilibrar o telemóvel na janela. Eu vou até si com o olhar clínico de quem já gravou dezenas de nichos diferentes e dirijo a sua gravação.": "No intentes equilibrar el móvil en la ventana. Voy hasta ti con la mirada experta de quien ha grabado decenas de sectores y dirijo tu grabación.", "Qualidade que vende:": "Calidad que vende:", "Legendas magnéticas, cortes precisos, som limpo e imagem profissional. O seu conteúdo vai destacar-se da concorrência e prender a atenção logo nos primeiros 3 segundos.": "Subtítulos magnéticos, cortes precisos, sonido limpio e imagen profesional. Tu contenido destacará y captará la atención en los primeros 3 segundos.",
	},
	fr: {
		"Fim do bloqueio criativo:": "Fini le blocage créatif :", "Não sabe o que gravar? Eu tenho formações em marketing e formatos virais. Crio os guiões e roteiros exatos para o seu nicho.": "Vous ne savez pas quoi filmer ? Formée au marketing et aux formats viraux, je crée les scénarios exacts pour votre secteur.", "Gravação sem stress:": "Un tournage sans stress :", "Nada de tentar equilibrar o telemóvel na janela. Eu vou até si com o olhar clínico de quem já gravou dezenas de nichos diferentes e dirijo a sua gravação.": "Inutile d'essayer de caler votre téléphone à la fenêtre. Je viens sur place et dirige votre tournage avec l'expérience de dizaines de secteurs.", "Qualidade que vende:": "Une qualité qui vend :", "Legendas magnéticas, cortes precisos, som limpo e imagem profissional. O seu conteúdo vai destacar-se da concorrência e prender a atenção logo nos primeiros 3 segundos.": "Des sous-titres magnétiques, des coupes précises, un son net et une image professionnelle. Votre contenu se démarquera dès les 3 premières secondes.",
	},
	de: {
		"Fim do bloqueio criativo:": "Schluss mit der kreativen Blockade:", "Não sabe o que gravar? Eu tenho formações em marketing e formatos virais. Crio os guiões e roteiros exatos para o seu nicho.": "Sie wissen nicht, was Sie aufnehmen sollen? Ich bin in Marketing und viralen Formaten ausgebildet und erstelle die passenden Skripte für Ihre Nische.", "Gravação sem stress:": "Stressfreies Filmen:", "Nada de tentar equilibrar o telemóvel na janela. Eu vou até si com o olhar clínico de quem já gravou dezenas de nichos diferentes e dirijo a sua gravação.": "Kein Balancieren des Telefons am Fenster. Ich komme zu Ihnen und führe Ihre Aufnahme mit der Erfahrung aus Dutzenden Branchen.", "Qualidade que vende:": "Qualität, die verkauft:", "Legendas magnéticas, cortes precisos, som limpo e imagem profissional. O seu conteúdo vai destacar-se da concorrência e prender a atenção logo nos primeiros 3 segundos.": "Magnetische Untertitel, präzise Schnitte, klarer Ton und ein professionelles Bild. Ihre Inhalte werden sich ab der ersten 3 Sekunden abheben.",
	},
};

Object.assign(missingPageTranslations.es, {
	"Analisamos o seu objetivo e eu crio os roteiros altamente persuasivos e virais. Você só tem de aprovar.": "Analizamos tu objetivo y creamos guiones muy persuasivos y virales. Solo tienes que aprobarlos.", "Marcamos o dia, eu vou ao seu espaço físico, ajusto o ambiente, dirijo a cena para ficar confortável e gravamos tudo com alta qualidade.": "Acordamos el día, voy a tu espacio, preparo el ambiente, dirijo la escena para que estés cómodo y grabamos todo con alta calidad.", "Pego em todo o material gravado, levo para a ilha de edição e aplico retenção pura: cortes, legendas, efeitos e correção de cor.": "Llevo todo el material grabado a la sala de edición y maximizo la retención con cortes, subtítulos, efectos y corrección de color.", "Em até 3 dias úteis após a gravação, os seus vídeos estão prontos numa pasta do Google Drive. É só descarregar e publicar.": "En un máximo de 3 días laborables después de la grabación, tus vídeos estarán listos en una carpeta de Google Drive. Solo tienes que descargarlos y publicarlos.", "Textos pensados para reter a atenção e converter seguidores em clientes.": "Textos pensados para retener la atención y convertir seguidores en clientes.", "Ajudo-o com a postura, tom de voz e naturalidade em frente às câmaras.": "Te ayudo con la postura, el tono de voz y la naturalidad frente a las cámaras.", "As palavras aparecem no ecrã no ritmo certo, com cores e fontes que combinam com a sua marca.": "Las palabras aparecen en pantalla al ritmo adecuado, con colores y fuentes que combinan con tu marca.", "Remoção de ruídos de fundo e correção de luz e cor.": "Eliminación del ruido de fondo y corrección de luz y color.", "Adicionamos cenas com direitos pagos para ilustrar o que está a dizer e manter o vídeo dinâmico.": "Añadimos imágenes con licencia para ilustrar lo que dices y mantener el vídeo dinámico.", "Fala diretamente comigo no WhatsApp. Sem robôs, sem intermediários.": "Habla directamente conmigo por WhatsApp. Sin robots ni intermediarios.", "Capto os bastidores e os momentos-chave em tempo real.": "Capto los momentos clave y el detrás de cámaras en tiempo real.", "Gravo conteúdos dinâmicos para os Stories e para o Feed com um olhar cinematográfico.": "Grabo contenido dinámico para Stories y Feed con una mirada cinematográfica.", "Transmito a energia e a autoridade do seu evento para quem está a ver de casa, enquanto tudo acontece.": "Transmito la energía y la autoridad de tu evento a quienes lo ven desde casa mientras todo sucede.", "Não deixe que o seu maior evento passe em branco nas redes sociais.": "No dejes que tu evento más importante pase desapercibido en las redes sociales."
});

Object.assign(missingPageTranslations.fr, {
	"Analisamos o seu objetivo e eu crio os roteiros altamente persuasivos e virais. Você só tem de aprovar.": "Nous analysons votre objectif et créons des scénarios très persuasifs et viraux. Vous n'avez plus qu'à les approuver.", "Marcamos o dia, eu vou ao seu espaço físico, ajusto o ambiente, dirijo a cena para ficar confortável e gravamos tudo com alta qualidade.": "Nous fixons le jour, je viens sur place, prépare l'environnement, dirige la scène pour votre confort et filme le tout en haute qualité.", "Pego em todo o material gravado, levo para a ilha de edição e aplico retenção pura: cortes, legendas, efeitos e correção de cor.": "J'emporte toutes les images tournées en salle de montage et maximise la rétention avec des coupes, sous-titres, effets et corrections colorimétriques.", "Em até 3 dias úteis após a gravação, os seus vídeos estão prontos numa pasta do Google Drive. É só descarregar e publicar.": "Sous 3 jours ouvrés après le tournage, vos vidéos sont prêtes dans un dossier Google Drive. Il suffit de les télécharger et de les publier.", "Textos pensados para reter a atenção e converter seguidores em clientes.": "Des textes conçus pour retenir l'attention et convertir les abonnés en clients.", "Ajudo-o com a postura, tom de voz e naturalidade em frente às câmaras.": "Je vous aide avec la posture, le ton de voix et l'aisance face aux caméras.", "As palavras aparecem no ecrã no ritmo certo, com cores e fontes que combinam com a sua marca.": "Les mots apparaissent à l'écran au bon rythme, avec des couleurs et des polices assorties à votre marque.", "Remoção de ruídos de fundo e correção de luz e cor.": "Suppression des bruits de fond et correction de la lumière et des couleurs.", "Adicionamos cenas com direitos pagos para ilustrar o que está a dizer e manter o vídeo dinâmico.": "Nous ajoutons des images sous licence pour illustrer vos propos et garder la vidéo dynamique.", "Fala diretamente comigo no WhatsApp. Sem robôs, sem intermediários.": "Échangez directement avec moi sur WhatsApp. Sans robots ni intermédiaires.", "Capto os bastidores e os momentos-chave em tempo real.": "Je capture les coulisses et les moments clés en temps réel.", "Gravo conteúdos dinâmicos para os Stories e para o Feed com um olhar cinematográfico.": "Je crée du contenu dynamique pour les Stories et le Feed avec un regard cinématographique.", "Transmito a energia e a autoridade do seu evento para quem está a ver de casa, enquanto tudo acontece.": "Je transmets l'énergie et l'autorité de votre événement à ceux qui le suivent depuis chez eux.", "Não deixe que o seu maior evento passe em branco nas redes sociais.": "Ne laissez pas votre événement le plus important passer inaperçu sur les réseaux sociaux."
});

Object.assign(missingPageTranslations.de, {
	"Analisamos o seu objetivo e eu crio os roteiros altamente persuasivos e virais. Você só tem de aprovar.": "Wir analysieren Ihr Ziel und erstellen überzeugende, virale Drehbücher. Sie müssen sie nur noch freigeben.", "Marcamos o dia, eu vou ao seu espaço físico, ajusto o ambiente, dirijo a cena para ficar confortável e gravamos tudo com alta qualidade.": "Wir vereinbaren den Termin, kommen zu Ihnen, richten die Umgebung ein, führen Sie sicher durch die Szene und filmen alles in hoher Qualität.", "Pego em todo o material gravado, levo para a ilha de edição e aplico retenção pura: cortes, legendas, efeitos e correção de cor.": "Ich bringe das gesamte Material in den Schnittraum und maximiere die Zuschauerbindung mit Schnitten, Untertiteln, Effekten sowie Farbkorrektur.", "Em até 3 dias úteis após a gravação, os seus vídeos estão prontos numa pasta do Google Drive. É só descarregar e publicar.": "Innerhalb von 3 Werktagen nach dem Dreh liegen Ihre Videos in einem Google-Drive-Ordner bereit. Herunterladen und veröffentlichen.", "Textos pensados para reter a atenção e converter seguidores em clientes.": "Texte, die Aufmerksamkeit halten und Follower in Kunden verwandeln.", "Ajudo-o com a postura, tom de voz e naturalidade em frente às câmaras.": "Ich helfe Ihnen mit Haltung, Stimme und Natürlichkeit vor der Kamera.", "As palavras aparecem no ecrã no ritmo certo, com cores e fontes que combinam com a sua marca.": "Die Wörter erscheinen im richtigen Rhythmus mit Farben und Schriften, die zu Ihrer Marke passen.", "Remoção de ruídos de fundo e correção de luz e cor.": "Entfernung von Hintergrundgeräuschen sowie Licht- und Farbkorrektur.", "Adicionamos cenas com direitos pagos para ilustrar o que está a dizer e manter o vídeo dinâmico.": "Wir ergänzen lizenziertes Bildmaterial, um Ihre Aussagen zu veranschaulichen und das Video dynamisch zu halten.", "Fala diretamente comigo no WhatsApp. Sem robôs, sem intermediários.": "Sprechen Sie direkt mit mir über WhatsApp. Keine Bots, keine Vermittler.", "Capto os bastidores e os momentos-chave em tempo real.": "Ich halte die Blicke hinter die Kulissen und die Schlüsselmomente in Echtzeit fest.", "Gravo conteúdos dinâmicos para os Stories e para o Feed com um olhar cinematográfico.": "Ich produziere dynamische Inhalte für Stories und Feed mit einem filmischen Blick.", "Transmito a energia e a autoridade do seu evento para quem está a ver de casa, enquanto tudo acontece.": "Ich vermittle die Energie und Autorität Ihrer Veranstaltung live an alle, die von zu Hause zuschauen.", "Não deixe que o seu maior evento passe em branco nas redes sociais.": "Lassen Sie Ihr wichtigstes Event in den sozialen Netzwerken nicht unbeachtet bleiben."
});

function getTranslationDictionaries() {
	return [pageTranslations, additionalPageTranslations, missingPageTranslations, authorityTranslations, translations];
}

function getOriginalText(value) {
	for (const dictionaries of getTranslationDictionaries()) {
		for (const dictionary of Object.values(dictionaries)) {
			const original = Object.keys(dictionary).find((key) => dictionary[key] === value);
			if (original) return original;
		}
	}
	return value;
}

function translateRenderedText(language) {
	const root = document.getElementById("root");
	if (!root) return;
	const dictionary = { ...pageTranslations[language], ...additionalPageTranslations[language], ...missingPageTranslations[language], ...authorityTranslations[language], ...benefitsTranslations[language], ...reportedTranslations[language], ...translations[language] };
	const walker = document.createTreeWalker(root, 4);
	let node;
	while ((node = walker.nextNode())) {
		const parent = node.parentElement;
		if (!parent || parent.closest("script, style")) continue;
		const original = getOriginalText(node.nodeValue);
		const trimmed = original.trim();
		if (!trimmed) continue;
		node.nodeValue = original.replace(trimmed, dictionary[trimmed] || trimmed);
	}
}

function translateRenderedPage(language) {
	const dictionary = pageTranslations[language] || {};
	const root = document.getElementById("root");
	if (!root) return;
	const translate = (value) => dictionary[value] || translations[language]?.[value] || value;
	const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
	let node;
	while ((node = walker.nextNode())) {
		if (!node.parentElement || ["SCRIPT", "STYLE"].includes(node.parentElement.tagName)) continue;
		const original = node.__potencializaOriginal ?? node.nodeValue;
		node.__potencializaOriginal = original;
		const trimmed = original.trim();
		if (!trimmed) continue;
		node.nodeValue = original.replace(trimmed, translate(trimmed));
	}
	root.querySelectorAll("[placeholder], [aria-label], [title]").forEach((element) => {
		["placeholder", "aria-label", "title"].forEach((attribute) => {
			const value = element.getAttribute(attribute);
			if (!value) return;
			const key = `potencializaOriginal${attribute}`;
			const original = element.dataset[key] || value;
			element.dataset[key] = original;
			element.setAttribute(attribute, translate(original));
		});
	});
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
	const [language, setLanguage] = useState(() => {
		const savedLanguage = localStorage.getItem("potencializa-language");
		return savedLanguage && languages[savedLanguage] ? savedLanguage : "pt";
	});

	useEffect(() => {
		localStorage.setItem("potencializa-language", language);
		document.documentElement.lang = languages[language].locale;
		const frame = requestAnimationFrame(() => translateRenderedText(language));
		return () => cancelAnimationFrame(frame);
	}, [language]);

	const value = useMemo(() => ({
		language,
		setLanguage,
		languages,
		t: (text) => translations[language]?.[text] || reportedTranslations[language]?.[text] || missingPageTranslations[language]?.[text] || additionalPageTranslations[language]?.[text] || authorityTranslations[language]?.[text] || benefitsTranslations[language]?.[text] || pageTranslations[language]?.[text] || text,
	}), [language]);

	return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
	const context = useContext(LanguageContext);
	if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
	return context;
}
